//
//  CharacterListScenePresenter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit

protocol ICharacterListScenePresenter: AnyObject {
    func fetchCharactersResponse(_ response: CharacterListSceneModels.FetchCharacters.Response)
    
    func fetchCharacterImageResponse(_ response: CharacterListSceneModels.FetchCharacterImage.Response)
    
    func showCharacterDetailResponse(_ response: CharacterListSceneModels.ShowCharacterDetail.Response)
    
    func showErrorResponse(_ response: CharacterListSceneModels.ShowError.Response)
}

class CharacterListScenePresenter{
    
    weak var vc: ICharacterListSceneDelegate?
    
    init(vc: ICharacterListSceneDelegate){
        self.vc = vc
    }
}

extension CharacterListScenePresenter: ICharacterListScenePresenter{
    // MARK: PRESENTATION LOGIC INTERFACE IMPLEMENTATIONS
    
    func fetchCharactersResponse(_ response: CharacterListSceneModels.FetchCharacters.Response){
        
        let vms = response.map{ CharacterListSceneModels.FetchCharacters.ViewModel(dtoCharacter: $0, isLoading: true)}
        
        self.vc?.didReceiveFetchCharactersViewModel(vms)
        
    }
    
    func fetchCharacterImageResponse(_ response: CharacterListSceneModels.FetchCharacterImage.Response){
        
        let img = response.characterImg == nil ? UIImage(named: "placeholder") : UIImage(data: response.characterImg!)
        
        let vm = CharacterListSceneModels.FetchCharacterImage.ViewModel(cellIndex: response.cellIndex, characterImg: img)
        
        vc?.didReceiveFetchCharacterImageViewModel(vm)
        
    }
    
    func showCharacterDetailResponse(_ response: CharacterListSceneModels.ShowCharacterDetail.Response){
        
        let img = response.studentImg == nil ? UIImage(named: "placeholder") : UIImage(data: response.studentImg!)
        
        vc?.showCharacterDetail(.init(character: response.detail, characterImg: img))
        
    }
    
    func showErrorResponse(_ response: CharacterListSceneModels.ShowError.Response){
        self.vc?.didReceiveError(.init(description: response.error.localizedDescription))
    }
}
