//
//  CharacterListSceneViewController.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit

// MARK: Controller Delegate
protocol ICharacterListSceneDelegate: AnyObject{
    func didReceiveFetchCharactersViewModel(_ vm: CharacterList.FetchCharacters.ViewModel)
    
    func didReceiveError(_ errorVm: CharacterList.ShowError.ViewModel)
    
    func showCharacterDetail(_ detail: CharacterList.ShowCharacterDetail.ViewModel)
}

class CharacterListSceneViewController: UIViewController {
    
    var router: ICharacterListSceneRouter!
    var interactor: ICharacterListSceneInteractor!
    var input: CharacterList.Input!
    
    // MARK: OUTLETS
    @IBOutlet weak var tableView: UITableView!
    
    private var _loadingView: LoadingView?
    private var _viewModel: CharacterList.FetchCharacters.ViewModel = .init(characters: [])
    private var _characters: [CharacterList.FetchCharacters.ViewModel.CharacterVm]{ _viewModel.characters }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
        if !isModal{
            NavBarCustomizer.defaultStyle(for: self)
        }else{
            let btnItem = UIBarButtonItem(barButtonSystemItem: .close, target: self, action: #selector(_didTapClose))
            NavBarCustomizer.defaultStyle(for: self, leftBarButton: btnItem, hideBackButton: true)
        }
        
        _loadingView = .loadView(into: self.view, autoPlay: false)
        _configureTableView()
        _fetchCharacters()
    }
    
    private func _configureTableView(){
        tableView.delegate = self
        tableView.dataSource = self
        CharacterTableViewCell.subscribe(to: tableView)
    }
    
    @objc private func _didTapClose(){
        router.dismissIfModal()
    }
}

extension CharacterListSceneViewController: UITableViewDelegate, UITableViewDataSource{
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        
        _characters.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: CharacterTableViewCell.cellId, for: indexPath) as! CharacterTableViewCell
        
        let character = _characters[indexPath.row]
        cell.configure(character: character)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        _showCharacterDetailRequest(cellIndex: indexPath)
        
        tableView.deselectRow(at: indexPath, animated: true)
    }
    
}

extension CharacterListSceneViewController: ICharacterListSceneDelegate{
    private func _fetchCharacters(){
        let request = CharacterList.FetchCharacters.Request(listType: input)
        _loadingView?.play()
        interactor.fetchCharactersRequest(request)
    }
    func didReceiveFetchCharactersViewModel(_ vm: CharacterList.FetchCharacters.ViewModel) {
        self._viewModel = vm
        tableView.reloadData()
        _loadingView?.stop()
    }
    
    func didReceiveError(_ errorVm: CharacterList.ShowError.ViewModel) {
//        Log.e(errorVm.description)
    }
    
    
    private func _showCharacterDetailRequest(cellIndex: IndexPath){
        let request = CharacterList.ShowCharacterDetail.Request(
            characterVm: _characters[cellIndex.row]
        )
        interactor.showCharacterDetailRequest(request)
    }
    func showCharacterDetail(_ detail: CharacterList.ShowCharacterDetail.ViewModel) {
        let dataPassing = CharacterList.CharacterDetailDataPassing(
            character: detail.character
        )
        self.router.showCharacterDetail(input: dataPassing)
    }
}
