//
//  CharacterListSceneModels.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml


import UIKit

struct CharacterListSceneModels {
    enum ListType{
        case house(HPHouse)
        case students
        case staff
    }
    
    typealias Input = ListType
}

// MARK: VIP - USE CASES
extension CharacterListSceneModels{
    // type `usecases` for magic
    struct FetchCharacters {
        
        typealias Request = ListType
        
        typealias Response = [DtoHpCharacter]
        
        struct ViewModel {
            let dtoCharacter: DtoHpCharacter
            var name: String{ dtoCharacter.name }
            var house: String{ dtoCharacter.house.rawValue }
            var isLoading: Bool
            var image: UIImage?
        }
    }
    
    struct FetchCharacterImage {
        
        struct Request{
            let cellIndex: IndexPath
            let dtoCharacter: DtoHpCharacter
        }
        
        struct Response {
            let cellIndex: IndexPath
            let characterImg: Data?
        }
        
        struct ViewModel {
            let cellIndex: IndexPath
            let characterImg: UIImage?
        }
    }
    
    struct ShowCharacterDetail {
        
        struct Request {
            let cellIndex: IndexPath
            let dtoCharacter: DtoHpCharacter
        }
        
        struct Response{
            let studentImg: Data?
            let detail: DtoHpCharacterDetail
        }
        
        typealias ViewModel = CharacterDetailSceneModels.Input
    }
    
    struct ShowError {
        
        struct Response {
            let error: Error
        }
        
        struct ViewModel {
            let description: String
        }
    }
}
