//
//  CharacterListSceneAdapter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Swinject
import SwiftRouting

extension CharacterListSceneViewController: XibImportable{}

class CharacterListSceneAdapter {
    
    private init() {}
    
    // MARK: Dependency Injection
    static func setup(input: CharacterListSceneModels.Input? = nil, assembler: Assembler? = nil) -> UIViewController{
        
        guard let assembler = assembler,
              let navigator = assembler.resolver.resolve(IAppNavigator.self),
              let hpService = assembler.resolver.resolve(HPService.self)
        else {
            fatalError("Dependencies not found")
        }
        
        let newAssembler = Assembler(parentAssembler: assembler)
        
        let controller = CharacterListSceneViewController.fromXib()
        let router = CharacterListSceneRouter(vc: controller)
        let presenter = CharacterListScenePresenter(vc: controller)
        let interactor = CharacterListSceneInteractor(presenter: presenter, hpService: hpService)
        
        controller.router = router
        controller.interactor = interactor
        controller.input = input
        
        router.assembler = newAssembler
        router.navigator = navigator
        
        return controller
    }
}
