//
//  CharacterDetailSceneRouter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 27/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit
import SwiftRouting
import Swinject

typealias ICharacterDetailSceneController = ICharacterDetailSceneDelegate & UIViewController

// MARK: Navigation Methods
protocol ICharacterDetailSceneRouter: AnyObject{

}

class CharacterDetailSceneRouter: IRouter {
    
    typealias Routes = Void
    
    weak var view: ICharacterDetailSceneController!
    var navigator: IAppNavigator?
    var assembler: Assembler?
    
    init(view: ICharacterDetailSceneController) {
        self.view = view
    }

}


extension CharacterDetailSceneRouter: ICharacterDetailSceneRouter{
    // MARK: NAVIGATION METHODS LOGIC INTERFACE IMPLEMENTATION
    
}
