//
//  CharacterDetailSceneModels.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 27/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit


struct CharacterDetailSceneModels {
    struct Input{
        private let _character: DtoHpCharacterDetail
        var characterImg: UIImage?
        var houseImg: UIImage?{ _character.house.img }
        var houseColor: UIColor{ _character.house.color }
        var gender: String{ _character.gender.capitalized }
        var species: String { _character.species.capitalized }
        var dateOfBirth: String{ _character.dateOfBirth }
        var alive: String{ _character.alive ? "Yes" : "No"}
        var wand: String{
            let core = _character.wand.core
            let wood = _character.wand.wood
            
            switch (core, wood){
            case ("", ""): return ""
            case ("", _): return wood
            case (_, ""): return core
            default: return "\(_character.wand.core.capitalized)\n\(_character.wand.wood.capitalized)"
            }
        }
        
        init(character: DtoHpCharacterDetail, characterImg: UIImage?){
            _character = character
            self.characterImg = characterImg
        }
    }
}

// MARK: Models for passing data to other routes
extension CharacterDetailSceneModels{
    
}


// MARK: VIP - USE CASES
extension CharacterDetailSceneModels{
    // type `usecases` for magic
}
