//
//  CharacterDetailScenePresenter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 27/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

protocol ICharacterDetailScenePresenter: AnyObject {
    
}

class CharacterDetailScenePresenter{
    
    weak var vc: ICharacterDetailSceneDelegate?
    
    init(vc: ICharacterDetailSceneDelegate){
        self.vc = vc
    }
}

extension CharacterDetailScenePresenter: ICharacterDetailScenePresenter{
    // MARK: PRESENTATION LOGIC INTERFACE IMPLEMENTATIONS
}
