//
//  CharacterDetailSceneRouter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 27/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit
import SwiftRouting
import Swinject

typealias ICharacterDetailSceneController = ICharacterDetailSceneDelegate & UIViewController

// MARK: Navigation Methods
protocol ICharacterDetailSceneRouter: AnyObject{
    func backToCharactersList()
}

class CharacterDetailSceneRouter: IRouter {
    
    enum AvailableRoutes{
        case characterLists
        case house
    }
    
    typealias Routes = AvailableRoutes
    
    weak var vc: ICharacterDetailSceneController!
    var navigator: IAppNavigator?
    var assembler: Assembler?
    
    init(vc: ICharacterDetailSceneController) {
        self.vc = vc
    }
    
    func showRoute(route: AvailableRoutes) {
        switch route {
        case .characterLists:
            navigator?.dismissModal(vc)
        case .house:
            break
        }
    }
}


extension CharacterDetailSceneRouter: ICharacterDetailSceneRouter{
    // MARK: NAVIGATION METHODS LOGIC INTERFACE IMPLEMENTATION
    func backToCharactersList(){
        showRoute(route: .characterLists)
    }
}
