//
//  StaffScenePresenter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit

protocol IStaffScenePresenter: AnyObject {
    func fetchStaffResponse(_ response: StaffSceneModels.FetchStaff.Response)
    
    func fetchStaffImageResponse(_ response: StaffSceneModels.FetchStaffImage.Response)
    
    func showCharacterDetailResponse(_ response: StaffSceneModels.ShowCharacterDetail.Response)
    
    func showErrorResponse(_ response: StaffSceneModels.ShowError.Response)
}

class StaffScenePresenter{
    
    weak var vc: IStaffSceneDelegate?
    
    init(vc: IStaffSceneDelegate){
        self.vc = vc
    }
}

extension StaffScenePresenter: IStaffScenePresenter{
    // MARK: PRESENTATION LOGIC INTERFACE IMPLEMENTATIONS
    func fetchStaffResponse(_ response: StaffSceneModels.FetchStaff.Response){
        let vms = response.map{ StudentsSceneModels.FetchStudents.ViewModel(dtoCharacter: $0, isLoading: true)}
        self.vc?.didReceiveFetchStaffViewModel(vms)
    }
    
    func fetchStaffImageResponse(_ response: StaffSceneModels.FetchStaffImage.Response){
        
        let img = response.studentImg == nil ? UIImage(named: "placeholder") : UIImage(data: response.studentImg!)
        
        let vm = StudentsSceneModels.FetchStudentImage.ViewModel(cellIndex: response.cellIndex, studentImg: img)
        
        vc?.didReceiveFetchStaffImageViewModel(vm)
    }
    
    func showCharacterDetailResponse(_ response: StaffSceneModels.ShowCharacterDetail.Response){
        let img = response.studentImg == nil ? UIImage(named: "placeholder") : UIImage(data: response.studentImg!)
        
        vc?.showCharacterDetail(.init(character: response.detail, characterImg: img))
    }
    
    func showErrorResponse(_ response: StaffSceneModels.ShowError.Response){
        self.vc?.didReceiveError(.init(description: response.error.localizedDescription))
    }

}
