//
//  StaffSceneRouter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml


typealias IStaffSceneRouter = IStudentsSceneRouter

typealias StaffSceneRouter = StudentsSceneRouter
