//
//  StaffSceneModels.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit

struct StaffSceneModels {}

// MARK: Models for passing data to other routes
extension StaffSceneModels{
    
}


// MARK: VIP - USE CASES
extension StaffSceneModels{
    // type `usecases` for magic
    
    typealias FetchStaff = StudentsSceneModels.FetchStudents
    
    typealias FetchStaffImage = StudentsSceneModels.FetchStudentImage
    
    typealias ShowCharacterDetail = StudentsSceneModels.ShowCharacterDetail
    
    
    struct ShowError {
        
        struct Response {
            let error: Error
        }
        
        struct ViewModel {
            let description: String
        }
    }
}
