//
//  HpStaffWorker.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

class HpStaffWorker {
    // MARK: Business Logic
    
    private let _hpService: HPService
    
    init(hpService: HPService){
        self._hpService = hpService
    }
    
    func getStaff(completion: @escaping (HPResult<[DtoHpCharacter]>)){
        _hpService.getStaff(completion: completion)
    }
    
    func getDetailOf(character: DtoHpCharacter) -> DtoHpCharacterDetail{
        _hpService.getCharacterDetail(character: character)
    }
}
