//
//  HpStudentImagesWorker.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 27/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Foundation

class HpStudentImagesWorker {
    // MARK: Business Logic
    
    private let _hpService: HPService
    
    init(hpService: HPService){
        self._hpService = hpService
    }
    
    func getStudentImage(character: DtoHpCharacter, completion: @escaping HPResult<Data>){
        _hpService.getImageOf(character: character, completion: completion)
    }
}
