//
//  HpStudentsWorker.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

class HpStudentsWorker {
    
    private let _hpService: HPService
    
    init(hpService: HPService){
        self._hpService = hpService
    }
    
    func getStudents(completion: @escaping (HPResult<[DtoHpCharacter]>)){
        _hpService.getStudents(completion: completion)
    }
}
