//
//  StudentsSceneScenePresenter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

protocol IStudentsScenePresenter: AnyObject {
    func fetchStudentsResponse(response: StudentsSceneModels.FetchStudents.Response)
    func showErrorResponse(response: StudentsSceneModels.ShowError.Response)
}

class StudentsScenePresenter{
    
    weak var view: IStudentsSceneDelegate?
    
    init(view: IStudentsSceneDelegate){
        self.view = view
    }
}

extension StudentsScenePresenter: IStudentsScenePresenter{
    // MARK: PRESENTATION LOGIC INTERFACE IMPLEMENTATIONS
    func fetchStudentsResponse(response: StudentsSceneModels.FetchStudents.Response){
        let vms = response.map{ StudentsSceneModels.FetchStudents.ViewModel(name: $0.name, house: $0.house, isLoading: true)}
        self.view?.didReceiveFetchStudentsViewModel(vms)
    }
    
    func showErrorResponse(response: StudentsSceneModels.ShowError.Response){
        self.view?.didReceiveError(.init(description: response.error.localizedDescription))
    }
}
