//
//  StudentsSceneSceneModels.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit


struct StudentsSceneModels {
}

// MARK: Models for passing data to other routes
extension StudentsSceneModels{
    struct CharacterDetailInput{
        var detail: DtoHpCharacterDetail
        var characterImg: UIImage?
    }
}


// MARK: VIP - USE CASES
extension StudentsSceneModels{
    // type `usecases` for magic
    struct FetchStudents {
        
        typealias Response = [DtoHpCharacter]
        
        struct ViewModel {
            var name: String
            var house: String
            var isLoading: Bool
            var image: UIImage?
        }
    }
    
    struct FetchStudentImage {
        
        struct Request{
            let cellIndex: IndexPath
        }
        
        struct Response {
            let cellIndex: IndexPath
            let studentImg: Data?
        }
        
        struct ViewModel {
            let cellIndex: IndexPath
            let studentImg: UIImage?
        }
    }
    
    struct ShowCharacterDetail {
        
        struct Request {
            let cellIndex: IndexPath
        }
        
        struct Response{
            let studentImg: Data?
            let detail: DtoHpCharacterDetail
        }
        
        typealias ViewModel = CharacterDetailInput
    }
    
    struct ShowError {
        
        struct Response {
            let error: Error
        }
        
        struct ViewModel {
            let description: String
        }
    }
}
