//
//  StudentsSceneSceneInteractor.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Foundation

// MARK: Interactor Requests interface
protocol IStudentsSceneInteractor: AnyObject{
    func fetchStudentsRequest()
    func fetchStudentImageRequest(_ request: StudentsSceneModels.FetchStudentImage.Request)
}

class StudentsSceneInteractor {
    
    var presenter: IStudentsScenePresenter
    private let _studentWorker: HpStudentsWorker
    private let _studentImagesWorker: HpStudentImagesWorker
    private var _studentModels: [DtoHpCharacter] = []
    
    init(presenter: IStudentsScenePresenter, hpService: HPService){
        self.presenter = presenter
        self._studentWorker = .init(hpService: hpService)
        self._studentImagesWorker = .init(hpService: hpService)
    }

}

extension StudentsSceneInteractor: IStudentsSceneInteractor{
    // MARK: BUSINESS LOGIC INTERFACE IMPLEMENTATIONS
    func fetchStudentsRequest(){
        _studentWorker.getStudents { [weak self] res in
            switch res{
            case .success(let students):
                self?._studentModels = students
                self?.presenter.fetchStudentsResponse(students)
            case .failure(let err):
                self?.presenter.showErrorResponse(.init(error: err))
            }
        }
    }
    
    func fetchStudentImageRequest(_ request: StudentsSceneModels.FetchStudentImage.Request){
        let selectedCharacter = _studentModels[request.cellIndex.row]
        _studentImagesWorker.getStudentImage(character: selectedCharacter) { [weak self] res in
            
            switch res{
            case .success(let img):
                let response = StudentsSceneModels.FetchStudentImage.Response(
                    cellIndex: request.cellIndex,
                    studentImg: img
                )
                self?.presenter.fetchStudentImageResponse(response)
                
            case .failure(let err):
                self?.presenter.showErrorResponse(.init(error: err))
            }
            
        }
    }
}
