//
//  StudentsSceneSceneModels.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit


struct StudentsSceneModels {
}

// MARK: Models for passing data to other routes
extension StudentsSceneModels{
    
}


// MARK: VIP - USE CASES
extension StudentsSceneModels{
    // type `usecases` for magic
    struct FetchStudents {
        
        typealias Response = [DtoHpCharacter]
        
        struct ViewModel {
            var name: String
            var house: String
            var isLoading: Bool
            var image: UIImage?
        }
    }
    
    struct ShowError {
        
        struct Response {
            let error: Error
        }
        
        struct ViewModel {
            let description: String
        }
    }
}
