//
//  StudentsSceneSceneRouter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit
import SwiftRouting
import Swinject

typealias IStudentsSceneController = IStudentsSceneDelegate & UIViewController

// MARK: Navigation Methods
protocol IStudentsSceneRouter: AnyObject{

}

enum ExampleRoutes {
    case example(input: StudentsSceneAdapter? = nil, assembler: Assembler? = nil)
}

class StudentsSceneRouter: IRouter {
    
    typealias Routes = ExampleRoutes
    
    weak var view: IStudentsSceneController!
    var navigator: IAppNavigator?
    var assembler: Assembler?
    
    init(view: IStudentsSceneController) {
        self.view = view
    }
    
    func showRoute(route: ExampleRoutes) {
        
        switch route{
        case .example(let input, let assembler): break
//            let controller = ExampleSceneAdapter.setup(input: input, assembler: assembler)
//            navigator?.go(from: view, to: controller)
        }
    }

}


extension StudentsSceneRouter: IStudentsSceneRouter{
    // MARK: NAVIGATION METHODS LOGIC INTERFACE IMPLEMENTATION
    
}
