//
//  StudentsSceneSceneAdapter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Swinject
import SwiftRouting

extension StudentsSceneViewController: XibImportable{}

class StudentsSceneAdapter {
    
    private init() {}
    
    // MARK: Dependency Injection
    static func setup(assembler: Assembler? = nil) -> UIViewController{
        
        guard let assembler = assembler,
              let navigator = assembler.resolver.resolve(IAppNavigator.self),
              let hpService = assembler.resolver.resolve(HPService.self)
        else {
            fatalError("Dependencies not found")
        }
        
        let newAssembler = Assembler(parentAssembler: assembler)
        
        let controller = StudentsSceneViewController.fromXib()
        let router = StudentsSceneRouter(view: controller)
        let presenter = StudentsScenePresenter(view: controller)
        let interactor = StudentsSceneInteractor(presenter: presenter, hpService: hpService)
        
        controller.router = router
        controller.interactor = interactor
        
        router.assembler = newAssembler
        router.navigator = navigator
        
        return controller
    }
}
