//
//  StudentsSceneSceneInteractor.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 23/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Foundation

// MARK: Interactor Requests interface
protocol IStudentsSceneInteractor: AnyObject{
    func fetchStudentsRequest()
}

class StudentsSceneInteractor {
    
    var presenter: IStudentsScenePresenter
    private let _studentWorker: HpStudentsWorker
    
    init(presenter: IStudentsScenePresenter, hpService: HPService){
        self.presenter = presenter
        self._studentWorker = HpStudentsWorker(hpService: hpService)
    }

}

extension StudentsSceneInteractor: IStudentsSceneInteractor{
    // MARK: BUSINESS LOGIC INTERFACE IMPLEMENTATIONS
    func fetchStudentsRequest(){
        _studentWorker.getStudents { [weak self] res in
            switch res{
            case .success(let students):
                self?.presenter.fetchStudentsResponse(response: students)
            case .failure(let err):
                self?.presenter.showErrorResponse(response: .init(error: err))
            }
        }
    }
}
