//
//  HpCharacterWorker.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

class HpCharacterWorker {
    private let _hpService: HPService
    
    init(hpService: HPService){
        self._hpService = hpService
    }
    
    func getStudents(completion: @escaping (HPResult<[DtoHpCharacter]>)){
        _hpService.getStudents(completion: completion)
    }
    
    func getStaff(completion: @escaping (HPResult<[DtoHpCharacter]>)){
        _hpService.getStaff(completion: completion)
    }
    
    func getHouseCharacters(house: HPHouse, completion: @escaping (HPResult<[DtoHpCharacter]>)){
        _hpService.getCharactersOf(house: house, completion: completion)
    }
    
    func getDetailOf(character: DtoHpCharacter) -> DtoHpCharacterDetail{
        _hpService.getCharacterDetail(character: character)
    }
}
