//
//  HousesSceneRouter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import UIKit
import SwiftRouting
import Swinject


// MARK: Navigation Methods
protocol IHousesSceneRouter: AnyObject{
    func showCharactersOf(house: HPHouse)
}

class HousesSceneRouter: IRouter {
    
    enum AvailableRoutes {
        case house(_ house: HPHouse)
    }
    
    typealias Routes = AvailableRoutes
    
    weak var vc: UIViewController!
    var navigator: IAppNavigator?
    var assembler: Assembler?
    
    init(vc: UIViewController) {
        self.vc = vc
    }
    
    func showRoute(route: AvailableRoutes) {
        
        switch route{
        case .house(let house):
            let controller = CharacterListSceneAdapter.setup(input: .house(house), assembler: assembler)
            navigator?.go(from: vc, to: controller, presentationType: .presentWithNavigation)
        }
    }

}


extension HousesSceneRouter: IHousesSceneRouter{
    // MARK: NAVIGATION METHODS LOGIC INTERFACE IMPLEMENTATION
    func showCharactersOf(house: HPHouse){
        showRoute(route: .house(house))
    }
}
