//
//  HousesSceneAdapter.swift
//  vip_architecture_example
//
//  Created by Lorenzo Limoli on 29/06/22.
//  Copyright (c) 2022 Lorenzo Limoli. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates
//  https://github.com/lore-lml

import Swinject
import SwiftRouting

extension HousesSceneViewController: XibImportable{}

class HousesSceneAdapter {
    
    private init() {}
    
    // MARK: Dependency Injection
    static func setup(assembler: Assembler? = nil) -> UIViewController{
        
        guard let assembler = assembler,
              let navigator = assembler.resolver.resolve(IAppNavigator.self)
        else {
            fatalError("Dependencies not found")
        }
        
        let newAssembler = Assembler(parentAssembler: assembler)
        
        let controller = HousesSceneViewController.fromXib()
        let router = HousesSceneRouter(vc: controller)
        
        controller.router = router
        
        router.assembler = newAssembler
        router.navigator = navigator
        
        return controller
    }
}
